// <!-- Application Logic -->
// Data for each step of the visualization
const stepsData = [
    {
        title: "The Concept & The Scenario",
        concept: `
            <p>The <strong>One-Sample T-test</strong> is an inferential statistical procedure. It is used to determine whether a sample of observations could have been generated by a process with a specific known (or hypothesized) population mean.</p>
            <p class="mt-4">It helps us answer the question: <em>"Is our sample significantly different from what we expected, or is the difference just due to random chance?"</em></p>
        `,
        example: `
            <p class="mb-4">A local bakery claims their famous Jumbo Chocolate Chip Cookies weigh exactly <strong>50 grams</strong> on average.</p>
            <p class="mb-4">You buy these cookies often and suspect they are actually smaller than advertised to save money. You decide to play the role of a statistician to test their claim.</p>
            <div class="bg-white p-4 rounded-lg border border-slate-200 text-center mt-6">
                <p class="text-sm text-slate-500 uppercase tracking-wide font-bold mb-1">Claimed Population Mean</p>
                <p class="text-3xl font-bold text-indigo-600">$$\\mu = 50\\text{g}$$</p>
            </div>
        `
    },
    {
        title: "Stating the Hypotheses",
        concept: `
            <p>Before analyzing data, we establish two mutually exclusive statements about the population:</p>
            <ul class="list-disc pl-5 mt-4 space-y-2">
                <li><strong>Null Hypothesis ($H_0$):</strong> The assumption of "no difference" or status quo. It assumes the sample belongs to the hypothesized population.</li>
                <li><strong>Alternative Hypothesis ($H_a$ or $H_1$):</strong> The claim we are trying to find evidence for. It suggests there is a statistically significant difference.</li>
            </ul>
        `,
        example: `
            <p>In our bakery scenario, we set up our hypotheses based on the bakery's claim of 50g.</p>
            <div class="space-y-4 mt-6">
                <div class="bg-white p-4 rounded-lg border border-slate-200 border-l-4 border-l-slate-400">
                    <p class="font-bold text-slate-700 mb-1">Null Hypothesis ($H_0$)</p>
                    <p class="text-slate-600">The true average weight of the cookies is 50g.</p>
                    <div class="text-center mt-2 text-xl">$$H_0: \\mu = 50$$</div>
                </div>
                <div class="bg-white p-4 rounded-lg border border-slate-200 border-l-4 border-l-indigo-500">
                    <p class="font-bold text-slate-700 mb-1">Alternative Hypothesis ($H_a$)</p>
                    <p class="text-slate-600">The true average weight of the cookies is NOT 50g (Two-tailed test).</p>
                    <div class="text-center mt-2 text-xl">$$H_a: \\mu \\neq 50$$</div>
                </div>
            </div>
        `
    },
    {
        title: "Collecting Sample Data",
        concept: `
            <p>Since we cannot weigh every single cookie the bakery has ever made (the population), we take a random <strong>sample</strong>.</p>
            <p class="mt-4">From this sample, we calculate key statistics that will represent the whole:</p>
            <ul class="list-disc pl-5 mt-2 space-y-1">
                <li><strong>Sample Size ($n$):</strong> Number of items observed.</li>
                <li><strong>Sample Mean ($\\bar{x}$):</strong> The average of our sample.</li>
                <li><strong>Sample Standard Deviation ($s$):</strong> How much the weights vary within our sample.</li>
            </ul>
        `,
        example: `
            <p>You go to the bakery and randomly purchase <strong>15 cookies</strong>.</p>
            <p class="mt-2">You weigh each one on a digital scale and calculate your sample statistics:</p>
            <div class="grid grid-cols-2 gap-4 mt-6">
                <div class="bg-white p-3 rounded border border-slate-200 text-center">
                    <p class="text-xs text-slate-500 uppercase font-bold">Sample Size</p>
                    <p class="text-xl font-bold text-slate-800">$$n = 15$$</p>
                </div>
                <div class="bg-white p-3 rounded border border-slate-200 text-center">
                    <p class="text-xs text-slate-500 uppercase font-bold">Sample Mean</p>
                    <p class="text-xl font-bold text-slate-800">$$\\bar{x} = 48\\text{g}$$</p>
                </div>
                <div class="col-span-2 bg-white p-3 rounded border border-slate-200 text-center">
                    <p class="text-xs text-slate-500 uppercase font-bold">Sample Standard Deviation</p>
                    <p class="text-xl font-bold text-slate-800">$$s = 3.2\\text{g}$$</p>
                </div>
            </div>
            <p class="mt-4 text-sm text-slate-600 italic">Our sample average is 48g, which is less than 50g. But is it low enough to prove the bakery wrong, or just a coincidence?</p>
        `
    },
    {
        title: "Significance & Degrees of Freedom",
        concept: `
            <p>Before calculating, we need to set a threshold for our decision and determine the shape of our distribution.</p>
            <p class="mt-4"><strong>Significance Level ($\\alpha$):</strong> The probability of rejecting the null hypothesis when it is actually true (false positive). Usually set to 0.05 (5%).</p>
            <p class="mt-4"><strong>Degrees of Freedom ($df$):</strong> Determines the exact shape of the T-distribution we use. It is based on sample size.</p>
        `,
        example: `
            <p>We want to be 95% confident in our conclusion, so we set our alpha level:</p>
            <div class="bg-white p-3 rounded border border-slate-200 text-center mt-4">
                <p class="text-xl font-bold text-slate-800">$$\\alpha = 0.05$$</p>
            </div>

            <p class="mt-6">Next, we calculate our Degrees of Freedom ($df$). The formula is $df = n - 1$.</p>
            <div class="bg-white p-3 rounded border border-slate-200 text-center mt-4">
                <p class="text-xl font-bold text-slate-800">$$df = 15 - 1 = 14$$</p>
            </div>
            <p class="mt-4 text-sm text-slate-600">We will use $df = 14$ and $\\alpha = 0.05$ to find our critical threshold later.</p>
        `
    },
    {
        title: "Calculating the T-Statistic",
        concept: `
            <p>The <strong>T-statistic</strong> measures how many standard errors our sample mean is away from the hypothesized population mean.</p>
            <p class="mt-4">A larger absolute t-value means the sample data provides stronger evidence against the null hypothesis.</p>
            <div class="bg-slate-100 p-4 rounded-lg mt-4 text-center">
                <p class="text-sm font-bold text-slate-600 mb-2">T-Statistic Formula</p>
                <p class="text-xl">$$t = \\frac{\\bar{x} - \\mu}{s / \\sqrt{n}}$$</p>
            </div>
        `,
        example: `
            <p>Let's plug our cookie data into the formula:</p>
            <ul class="list-none space-y-1 text-sm text-slate-600 mt-2 mb-4 bg-white p-3 rounded border border-slate-200">
                <li>$\\bar{x}$ (Sample Mean) = 48</li>
                <li>$\\mu$ (Population Mean) = 50</li>
                <li>$s$ (Std Deviation) = 3.2</li>
                <li>$n$ (Sample Size) = 15</li>
            </ul>
            <div class="overflow-x-auto">
                <p class="text-lg">$$t = \\frac{48 - 50}{3.2 / \\sqrt{15}}$$</p>
                <p class="text-lg mt-2">$$t = \\frac{-2}{3.2 / 3.87}$$</p>
                <p class="text-lg mt-2">$$t = \\frac{-2}{0.826}$$</p>
                <p class="text-2xl font-bold text-indigo-600 text-center mt-4">$$t \\approx -2.42$$</p>
            </div>
        `
    },
    {
        title: "Making the Decision",
        concept: `
            <p>We compare our calculated <strong>T-statistic</strong> to a <strong>Critical T-value</strong> from a standardized T-table (based on $df$ and $\\alpha$).</p>
            <p class="mt-4">If our calculated t-value falls outside the critical values (into the "rejection region"), the result is statistically significant.</p>
            <div class="mt-6 border border-slate-200 rounded-lg overflow-hidden bg-white">
                <svg viewBox="0 0 500 220" class="w-full h-auto">
                    <!-- Baseline -->
                    <line x1="20" y1="180" x2="480" y2="180" stroke="#94a3b8" stroke-width="2"/>
                    <!-- Bell Curve Approximation -->
                    <path d="M 30 180 C 130 180, 160 20, 250 20 C 340 20, 370 180, 470 180" fill="none" stroke="#4f46e5" stroke-width="3"/>

                    <!-- Left Rejection Region Shading -->
                    <path d="M 30 180 C 70 180, 100 130, 115 105 L 115 180 Z" fill="#ef4444" opacity="0.3"/>
                    <!-- Right Rejection Region Shading -->
                    <path d="M 470 180 C 430 180, 400 130, 385 105 L 385 180 Z" fill="#ef4444" opacity="0.3"/>

                    <!-- Vertical Lines for Critical Values -->
                    <line x1="115" y1="105" x2="115" y2="180" stroke="#ef4444" stroke-width="2" stroke-dasharray="4"/>
                    <line x1="385" y1="105" x2="385" y2="180" stroke="#ef4444" stroke-width="2" stroke-dasharray="4"/>

                    <!-- Calculated T-stat line -->
                    <line x1="85" y1="150" x2="85" y2="180" stroke="#000" stroke-width="3"/>
                    <text x="85" y="140" text-anchor="middle" font-size="12" font-weight="bold">-2.42</text>
                    <circle cx="85" cy="180" r="4" fill="#000"/>

                    <!-- Text Labels -->
                    <text x="250" y="200" text-anchor="middle" font-size="12" font-weight="bold">0 (Mean)</text>
                    <text x="115" y="200" text-anchor="middle" font-size="12" fill="#ef4444">-2.145</text>
                    <text x="385" y="200" text-anchor="middle" font-size="12" fill="#ef4444">+2.145</text>
                    <text x="70" y="60" font-size="12" fill="#ef4444">Rejection</text>
                    <text x="70" y="75" font-size="12" fill="#ef4444">Region</text>
                </svg>
            </div>
        `,
        example: `
            <p>Looking at a T-table for a two-tailed test with $df = 14$ and $\\alpha = 0.05$, the critical values are <strong>$\\pm 2.145$</strong>.</p>
            <p class="mt-4">Our calculated T-statistic is <strong>$-2.42$</strong>.</p>
            <div class="bg-red-50 p-4 rounded-lg border border-red-200 mt-6">
                <p class="font-bold text-red-700 mb-2">The Comparison:</p>
                <p class="text-red-900 font-mono text-center">$$-2.42 < -2.145$$</p>
                <p class="text-red-800 mt-2">Since our value is further from zero than the critical boundary, it falls into the rejection region.</p>
            </div>
            <div class="bg-green-50 p-4 rounded-lg border border-green-200 mt-4">
                <p class="font-bold text-green-800 mb-1">Conclusion:</p>
                <p class="text-green-900">We <strong>reject the Null Hypothesis</strong>. There is statistically significant evidence to conclude that the bakery's cookies do not average 50 grams.</p>
            </div>
        `
    },
    {
        title: "Recap & Formula Sheet",
        concept: `
            <p>You have successfully performed a One-Sample T-test! Here is a recap of the steps you took:</p>
            <ol class="list-decimal pl-5 mt-4 space-y-2 text-sm">
                <li>State Null ($H_0$) and Alternative ($H_a$) hypotheses.</li>
                <li>Determine sample mean ($\\bar{x}$) and standard dev ($s$).</li>
                <li>Choose significance level ($\\alpha$) and calculate $df$.</li>
                <li>Compute the T-statistic using the formula.</li>
                <li>Compare to critical values to make a final decision.</li>
            </ol>
            <p class="mt-6 text-indigo-600 font-semibold italic">Because of your statistical analysis, the bakery might need to update their labels or bake slightly larger cookies! 🍪</p>
        `,
        example: `
            <h4 class="font-bold text-slate-800 mb-4 border-b pb-2">Complete Formula Sheet</h4>
            <div class="space-y-4 overflow-x-auto text-sm md:text-base">
                <div class="flex flex-col bg-white p-3 rounded shadow-sm border border-slate-100">
                    <span class="text-slate-500 font-semibold text-xs uppercase">Sample Mean</span>
                    <span>$$\\bar{x} = \\frac{\\sum x_i}{n}$$</span>
                </div>
                <div class="flex flex-col bg-white p-3 rounded shadow-sm border border-slate-100">
                    <span class="text-slate-500 font-semibold text-xs uppercase">Sample Standard Deviation</span>
                    <span>$$s = \\sqrt{\\frac{\\sum (x_i - \\bar{x})^2}{n-1}}$$</span>
                </div>
                <div class="flex flex-col bg-white p-3 rounded shadow-sm border border-slate-100">
                    <span class="text-slate-500 font-semibold text-xs uppercase">Standard Error</span>
                    <span>$$SE = \\frac{s}{\\sqrt{n}}$$</span>
                </div>
                <div class="flex flex-col bg-white p-3 rounded shadow-sm border border-slate-100">
                    <span class="text-slate-500 font-semibold text-xs uppercase">T-Statistic</span>
                    <span>$$t = \\frac{\\bar{x} - \\mu}{SE} = \\frac{\\bar{x} - \\mu}{s / \\sqrt{n}}$$</span>
                </div>
                <div class="flex flex-col bg-white p-3 rounded shadow-sm border border-slate-100">
                    <span class="text-slate-500 font-semibold text-xs uppercase">Degrees of Freedom</span>
                    <span>$$df = n - 1$$</span>
                </div>
            </div>
        `
    }
];

let currentStep = 0;
const totalSteps = stepsData.length;

// DOM Elements
const elTitle = document.getElementById('step-title');
const elBadge = document.getElementById('step-badge');
const elConcept = document.getElementById('step-concept');
const elExample = document.getElementById('step-example');
const elProgressBar = document.getElementById('progress-bar');
const btnPrev = document.getElementById('btn-prev');
const btnNext = document.getElementById('btn-next');
const stepContainer = document.getElementById('step-container');
const indicatorContainer = document.getElementById('step-indicator');
const contentArea = document.getElementById('content-area');

function init() {
    // Generate dots indicator
    for (let i = 0; i < totalSteps; i++) {
        const dot = document.createElement('span');
        dot.className = `inline-block w-2.5 h-2.5 rounded-full mx-1 transition-colors duration-300 ${i === 0 ? 'bg-indigo-600' : 'bg-slate-300'}`;
        dot.id = `dot-${i}`;
        indicatorContainer.appendChild(dot);
    }
    renderStep();
}

function renderStep() {
    const data = stepsData[currentStep];

    // Trigger reflow for fade animation
    stepContainer.classList.remove('fade-in');
    void stepContainer.offsetWidth; // trigger reflow
    stepContainer.classList.add('fade-in');

    // Scroll content area back to top
    contentArea.scrollTop = 0;

    // Update Text Content
    elBadge.innerText = `Step ${currentStep + 1} of ${totalSteps}`;
    elTitle.innerText = data.title;
    elConcept.innerHTML = data.concept;

    // Update the Example layout slightly for the last step
    if (currentStep === totalSteps - 1) {
        elExample.parentElement.querySelector('h3').innerHTML = `<span class="text-2xl mr-2">📚</span> Formulas`;
    } else {
        elExample.parentElement.querySelector('h3').innerHTML = `<span class="text-2xl mr-2">🍪</span> The Bakery Scenario`;
    }
    elExample.innerHTML = data.example;

    // Update Progress Bar & Dots
    elProgressBar.style.width = `${((currentStep + 1) / totalSteps) * 100}%`;

    for (let i = 0; i < totalSteps; i++) {
        const dot = document.getElementById(`dot-${i}`);
        if (i === currentStep) {
            dot.classList.remove('bg-slate-300');
            dot.classList.add('bg-indigo-600');
        } else {
            dot.classList.remove('bg-indigo-600');
            dot.classList.add('bg-slate-300');
        }
    }

    // Update Buttons State
    btnPrev.disabled = currentStep === 0;

    if (currentStep === totalSteps - 1) {
        btnNext.disabled = true;
        btnNext.innerHTML = `Finish <svg class="w-5 h-5 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path></svg>`;
    } else {
        btnNext.disabled = false;
        btnNext.innerHTML = `Next <svg class="w-5 h-5 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path></svg>`;
    }

    // Tell MathJax to re-render any LaTeX mathematical formulas on the new page
    if (window.MathJax) {
        MathJax.typesetPromise([elConcept, elExample]).catch(function (err) {
            console.log('MathJax processing error: ', err.message);
        });
    }
}

function changeStep(direction) {
    const newStep = currentStep + direction;
    if (newStep >= 0 && newStep < totalSteps) {
        currentStep = newStep;
        renderStep();
    }
}

// Initialize App
document.addEventListener('DOMContentLoaded', init);